### ISSUE TITLE
Reverse proxy to operate on port 80

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [CodeChefVIT/deployments#10]
Use **nginx** to proxy requests to the desired application in the multi-tennant VM after `<IP>/projects/<project-name>`

**Comment by DiptoChakrabarty** [comment]
Is this like a haproxy where I have to assign a LoadBalancer which the user interacts but the traffic is handled by server running in the back

**Comment by L04DB4L4NC3R** [comment]
Yes. But in addition to load balancing you would always have proxied redirects. So lets say your server runs on port 3002 and the health route is `<ip>:3002/health`. With a proxy you can do this: `<ip>:80/<service-name>/health`

**Comment by L04DB4L4NC3R** [comment]
This is helpful for us bevause we will be deploying servers running on different ports but we still want to reach them using port 80. So we will do route level proxy

**Comment by DiptoChakrabarty** [comment]
Do you I need to use Swarm in this case for loadbalancing

**Comment by DiptoChakrabarty** [comment]
![Screenshot (172)](https://user-images.githubusercontent.com/45638240/64480766-60057180-d1eb-11e9-88e5-62bd03059967.png)
Getting this error while linking for proxy server

**Comment by DiptoChakrabarty** [comment]
I am facing some issues with the proxy redirection , its still happening partially

**Comment by L04DB4L4NC3R** [comment]
What do you mean partially?

**Comment by DiptoChakrabarty** [comment]
Like its redirecting like this 
![Screenshot (201)](https://user-images.githubusercontent.com/45638240/66761027-d9664300-eec0-11e9-927e-a6b7d8c56496.png)
this is common entry sign up page 

![Screenshot (203)](https://user-images.githubusercontent.com/45638240/66761078-ec791300-eec0-11e9-8d1b-3456cc9c564b.png)
this is the login page
![Screenshot (202)](https://user-images.githubusercontent.com/45638240/66761037-dc613380-eec0-11e9-9e57-c836343ac480.png)
this is hack insider

**Comment by L04DB4L4NC3R** [comment]
This is an issue with static file resolution in nginx
https://stackoverflow.com/questions/41152772/cant-serve-static-files-in-nodejs-and-nginx

**Comment by L04DB4L4NC3R** [comment]
The url in the last photo should be `<base-url>/<app-name>/signin`

**Comment by DiptoChakrabarty** [comment]
> The url in the last photo should be `<base-url>/<app-name>/signin`

I set up manual entries  like   <ip-addr>/hack-insider/services for each case in the conf file  its working like that

**Comment by L04DB4L4NC3R** [comment]
> > The url in the last photo should be `<base-url>/<app-name>/signin`
> 
> I set up manual entries like /hack-insider/services for each case in the conf file its working like that

No need for that. Your base url proxy pass will take care of that. Define upstream servers

**Comment by L04DB4L4NC3R** [comment]
Also, defining upstream servers is a good practice

**Comment by DiptoChakrabarty** [comment]
![Screenshot from 2019-12-05 03-21-08](https://user-images.githubusercontent.com/45638240/70184799-967d5a80-170e-11ea-984b-06a09fa2e21b.png)
This is output when I add container names to upstream

**Comment by L04DB4L4NC3R** [comment]
This issue has been resolved
