### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by DiptoChakrabarty** [CodeChefVIT/deployments#12]
When I do a docker-compose up and the containers are running there is no issue of login everything works fine .
However when I close the command (Ctrl C) the containers stop , even if I start the containers  then I am unable to login  I think this is an issue with mongodb .
I have set Selinux to be permissive permanently .

**Comment by L04DB4L4NC3R** [comment]
Start the containers in detach mode 
```bash
docker-compose up -d
```

**Comment by L04DB4L4NC3R** [comment]
What is the error you're getting when loggin in? Can you post a screenshot?

**Comment by DiptoChakrabarty** [comment]
> What is the error you're getting when loggin in? Can you post a screenshot?

This is whats happening when I  try to login without a docker-compose up or without entering the cloud 
![Screenshot (143)](https://user-images.githubusercontent.com/45638240/63023712-43636b80-bec3-11e9-9e22-be4de6dde677.png)
![Screenshot (144)](https://user-images.githubusercontent.com/45638240/63023714-43636b80-bec3-11e9-9f3e-ce29994cd84f.png)

**Comment by L04DB4L4NC3R** [comment]
Cannot see the screenshot. Btw it will only work on containers since we defined mongo container target in the connection URI. So no point in running it outside of the compose

**Comment by DiptoChakrabarty** [comment]
So the application will only run with a docker-compose up , the containers are started and running but unless I do a docker-compose  up I cannot use the application

**Comment by L04DB4L4NC3R** [comment]
So what is the problem? Do a `docker-compose up -d` to start the containers in the background

**Comment by DiptoChakrabarty** [comment]
The containers are running in the background  (using -d) , however its not able to login even after that , only when docker-compose up is running does the application work fully

**Comment by L04DB4L4NC3R** [comment]
> The containers are running in the background (using -d) , however its not able to login even after that , only when docker-compose up is running does the application work fully

That is very strange. Come to my room tomorrow and we'll sort it out

**Comment by L04DB4L4NC3R** [comment]
@DiptoChakrabarty Was this issue resolved?

**Comment by DiptoChakrabarty** [comment]
The application is working now , I fixed the issues

**Comment by DiptoChakrabarty** [comment]
Yes I have checked and sorted the previous issue which was coming

**Comment by L04DB4L4NC3R** [comment]
Cool. Closing this issue now. Let me know what else is left in the CET deployment
