### ISSUE TITLE
Free slot finder deployment

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [CodeChefVIT/deployments#13]
Use ubuntu container and install python and node.js in it as this project uses the python shell also

**Comment by DiptoChakrabarty** [comment]
Deployed the application on port 3000 , error after providing data  (problem faced by creators of the project also)

**Comment by L04DB4L4NC3R** [comment]
Can you post a screenshot of the said error?

**Comment by DiptoChakrabarty** [comment]
![Screenshot (159)](https://user-images.githubusercontent.com/45638240/64048290-f358fa00-cb8e-11e9-9711-2387a94c6d71.png)
Entering The Details
![Screenshot (160)](https://user-images.githubusercontent.com/45638240/64048293-f522bd80-cb8e-11e9-8857-e6780738e0ea.png)
This is the response

**Comment by L04DB4L4NC3R** [comment]
And what were the logs?

**Comment by DiptoChakrabarty** [comment]
It seems that  module PIL is not present   from the docker-compose logs

**Comment by L04DB4L4NC3R** [comment]
Then it might be an error in their `package.json`. Ill clone it and see

**Comment by L04DB4L4NC3R** [comment]
Found the bug. The reasons were the following:

* Nodejs script invokes a python script which has its own dependancies, but no requirements file was made to install.

* Python path needed to be defined while executing the script from python shell.

I have pushed to the FSF repo. You can pull the latest changes. What you need to do to make it run is:

```bash
sudo apt install python-pip
pip install -r requirements.txt
```
Add these lines inside the docker image ^

**Comment by DiptoChakrabarty** [comment]
I am getting the outputs but they vary a bit
![Screenshot (171)](https://user-images.githubusercontent.com/45638240/64423196-8b8d3c80-d0c3-11e9-9771-48a32cf7b040.png)
Output in Windows
![Screenshot (170)](https://user-images.githubusercontent.com/45638240/64423209-934ce100-d0c3-11e9-9b3f-987609c3d791.png)
Output in Linux
![Screenshot (169)](https://user-images.githubusercontent.com/45638240/64423220-9a73ef00-d0c3-11e9-8abc-e964e1be5a91.png)
Data Is coming , but mozilla(of linux vm) is unable to display it

**Comment by L04DB4L4NC3R** [comment]
The user won't be using the Mozilla of a VM. They'll hit the site through their own browser. So no issues

**Comment by DiptoChakrabarty** [comment]
Ok Ill push my docker image to  docker hub and update the changes for the repo .

**Comment by DiptoChakrabarty** [comment]
Free Slot Finder has been deployed can this issue be closed
