### ISSUE TITLE
unable to determine fix for error

### ISSUE THREAD

**Issue by DiptoChakrabarty** [CodeChefVIT/deployments#2]
![Screenshot (129)](https://user-images.githubusercontent.com/45638240/62012622-2e3dcb80-b1a6-11e9-8a8e-2dabc8b0cf32.png)
![Screenshot (130)](https://user-images.githubusercontent.com/45638240/62012623-2ed66200-b1a6-11e9-83ab-9fd1de93a851.png)

**Comment by L04DB4L4NC3R** [comment]
This error arises due to the lack of `node_modules` which is due to the fact that the project uses some libraries which haven't yet been installed. 

Add the following command:

```bash
# Install node modules
$ npm install
```

**Comment by L04DB4L4NC3R** [comment]
@DiptoChakrabarty Close this issue if resolved

**Comment by DiptoChakrabarty** [comment]
Its showing the same error 
1) Cannot find module express
2) throw err
I have added npm install  but these 2 errors remains

**Comment by L04DB4L4NC3R** [comment]
The modules to install is defined in `package.json`. Make sure you copy it into the container before running `npm install`

**Comment by DiptoChakrabarty** [comment]
yes the express part has been fixed there is another minor error now of file not found , will debug and update  soon

**Comment by L04DB4L4NC3R** [comment]
Cool. Closing this issue now
