### ISSUE TITLE
use docker images in compose

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [CodeChefVIT/deployments#3]
Make a docker image and use that in the `docker-compose.yml`. This will allow you to remove all other code from this repo and build the images from a different repo.

The aim is to keep this repo for deployment configs

**Comment by L04DB4L4NC3R** [comment]
@DiptoChakrabarty What all is left to do from your side when it comes to this project?

**Comment by DiptoChakrabarty** [comment]
I have deployed the container , I can add an ansible playbook  for automation in different servers 
Rest Deployment is Done

**Comment by L04DB4L4NC3R** [comment]
Send me the host and port of the server on whatsapp
